sudo: false
language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g gulp grunt-cli
deploy:
  provider: npm
  email: contact@tiste.org
  api_key:
    secure: BXZkpcgWEgdZYI+qb2BKIshHa38H8zKI2gVjgqQA//XgYzgQ4hxK2Ab0peL3vKB+DmPcn9WDfnHPQBrQbpUwIvxFjNIuKMRG1FG5jjyQjnr2sBaj8A0Pb7S+v/LmVGYBO4KbPD7pPjYhA+mm7AkG7c+MCFdUKJ0kaCSD4qh9yR8=
  on:
    tags: true
    repo: legacy-icons/famfamfam-mini
